Practice day3 shrasti
muskan3006/interns-training pull request #6
Opened 2023-04-20 13:13 UTC by Shrasti0207

Practice On Pattern Matching , Sealed Class and list

2023-05-03 05:19 UTC, muskan3006 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +    case num if num % 2 == 0 => s"$num is even"
num is not good name

2023-05-03 05:20 UTC, muskan3006 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +  inputList.flatten(x => x)
what is x? and do we even require this expression(x => x) here? what else way we can do that?

2023-05-03 05:21 UTC, muskan3006 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +case class sum(num1: Int, num2: Int) extends Experiment
naming convention wrong

2023-05-03 05:21 UTC, muskan3006 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +def describe(e: Experiment): String = e match {
naming convention

2023-05-03 05:26 UTC, muskan3006 requested changes
please resolve the comment and update PR with latest main

2023-05-03 06:04 UTC, Shrasti0207 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +    case num if num % 2 == 0 => s"$num is even"
I have solved num into matchNumber

2023-05-03 06:05 UTC, Shrasti0207 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +  inputList.flatten(x => x)
I have solved

2023-05-03 06:05 UTC, Shrasti0207 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +case class sum(num1: Int, num2: Int) extends Experiment
I have solved num1 into inputNumber1 and num2 into inputNumber2

2023-05-03 06:06 UTC, Shrasti0207 commented on scala-practice/src/main/scala/ScalaPracticeDay3.sc
> +def describe(e: Experiment): String = e match {
e updated into expression

2023-05-04 12:01 UTC, muskan3006 approved these changes

2023-05-04 12:05 UTC, merged